### ISSUE TITLE
Example Not Working

### ISSUE THREAD

**Issue by Manason** [project-error/svelte-lua-boilerplate#41]
Cloned the repo as a resource, loaded into my server, then typed "svelte:show" into a client console. This set the NUI focus but I saw no UI displayed. ESC did not take me out of focus. I added console.logs in the script portion of HelloWorld.svelte and did not see any output in console. I repeated these experiments using both npm run dev, and npm run build

Lastly, it should be noted that the out of game browser functionality works fine.

**Comment by LukeWasTakenn** [comment]
Resolved in commit 0deabbd0a1aff0befe46d24944f164e2bdd2dfa7

Thanks for reporting.
